### PR TITLE
Add server behavior details for Http503VerbosityLevel

### PR DESCRIPTION
**Pull request by smflorentino**
Add additional details on the HTTP Server behavior for some of the `Http503VerbosityLevel` values.

### CODE REVIEW

**Comment by scottaddie** [comment]
Docs Build status updates of commit _[61bd511](https://github.com/smflorentino/AspNetApiDocs/commits/61bd511b39c09d4c4d993b9c7bfd73633629cad5)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[aspnet-core/xml/Microsoft.AspNetCore.Server.HttpSys/Http503VerbosityLevel.xml](https://github.com/smflorentino/AspNetApiDocs/blob/scflor/http503verbosity/aspnet-core/xml/Microsoft.AspNetCore.Server.HttpSys/Http503VerbosityLevel.xml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.server.httpsys.http503verbositylevel?view=aspnetcore-2.1&branch=pr-en-us-182) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C8%5Cbaf25683-9e81-c379-8ba7-62f30178bab2%5CPullRequest%5C202012080236399398-182%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=51%2FFotQWUQUaQuXmgka34900stTujQmbmr42Y4PWuCI%3D&st=2020-12-08T02%3A35%3A12Z&se=2021-01-08T02%3A40%3A12Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/baf25683-9e81-c379-8ba7-62f30178bab2?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by Tratcher** [comment]
Aren't these docs pulled from the src, so changes in this repo would be overwritten?
https://github.com/dotnet/aspnetcore/blob/e14e5bc7f215c6f86f2b02882affdff758fb265b/src/Servers/HttpSys/src/Http503VerbosityLevel.cs#L9

**Comment by smflorentino** [comment]
I don't know. If that is the case, why are these in source control at all?

**Comment by guardrex** [comment]
@Tratcher ... Yes, that's right. I'll let Scott comment further on this ... this is more in his area.

@smflorentino ... My understanding of the process is limited, but API docs must be published to doc web hosting servers ... Azure hosting no doubt :smile:. The content for the docs websites can't be created directly from product unit repos (source control). The docs are generated from here ... a docs repo set up for this purpose. Scott will correct me if I'm mistaken on any of that.

You'd need to submit a PR to the product unit to change the API remarks.

**_Please open an issue first to float your suggested text and offer to submit a PR at_** ...

https://github.com/dotnet/aspnetcore/issues

They welcome community support, but it's best to ask and iron out the lingo before work is done and submitted for anything more than a trivial change (e.g., a misspelled word).

**Comment by smflorentino** [comment]
>The docs are generated from here ... a docs repo set up for this purpose acting as in intermediary between source control and published docs. Scott will correct me if I'm mistaken on any of that.

Maybe I should be understanding the below readme better in this repo, but the current one is a bit terse. Once we get clarity, can we update the `readme.md` and/or `CONTRIBUTING.md` in this repo? Maybe clarifying *which* types of PRs should *actually* be made here.

>API PR's ( api/autoapi/... ) should not be made here. Changes to API documentation should be made in the source repository against the triple slash /// comments.

**Pull request closed without merging**
