### PR TITLE
Updating the Microsoft.AspNetCore.StaticFiles

### PR DESCRIPTION
**Pull request by merrua**
ASP.NET Core API Reference adding descriptions. I've added the description to Microsoft.AspNetCore.StaticFiles

### CODE REVIEW

**Comment by merrua** [comment]
@danroth27 Would it be easier if I made changes in one pull request? Or are small changes easier to manage?

**Comment by danroth27** [comment]
@merrua One PR would probably be easier to manage. You might want to hold off a bit though to save yourself some work. I was chatting with @Eilon and we were going to do a quick pass through the namespace descriptions.

**Comment by Rick-Anderson** [comment]
Per https://github.com/aspnet/ApiDocs/blob/master/README.md
API PR's ( *api/autoapi/...* ) should not be made here. Changes to API documentation should be made in the source repository against the triple slash /// comments.

**Comment by Rick-Anderson** [comment]
Closing because merge conflicts.  

f you want to resubmit this change again, I'll be sure to get it quickly reviewed. Sorry this has been sitting for so long.

**Pull request closed without merging**
