### PR TITLE
CI Update

### PR DESCRIPTION
**Pull request by v-alje**
Build.Reason:Manual by Alma Jenks
 Build.Url:https://apidrop.visualstudio.com/Content%20CI/_build/results?buildId=167876&view=results
 source_repo.branch:master
 source_repo.url:https://apidrop.visualstudio.com/_git/binaries

### CODE REVIEW

**Review by scottaddie — APPROVED** [review]
This looks good to me. We'll need these APIs to publish on November 10th.

**Review by mkArtakMSFT — APPROVED** [review]

**Comment by Rick-Anderson** [comment]
@v-alje  @scottaddie  are all the warnings expected?

**Comment by Rick-Anderson** [comment]
@scottaddie  can we merge this  now to prevent merge conflicts in other PR's? We won't merge to live until Nov 10th. Not sure why we need to wait for that.

**Comment by v-alje** [comment]
The warnings are for private members, or external libraries that we do not document.
Sure, I'll merge to master.

**Pull request merged**
